### ISSUE TITLE
Delegation UI text issues

### ISSUE THREAD

**Issue by orhoj** [Concordium/concordium-desktop-wallet#268]
**Bug Description**
The text when delegating to the L-pool is confusing as it refers to an active baker, and there is some extra text that can be deleted.

**Steps to Reproduce**

1. Select an account.
2. Select "Delegate to a pool".

**Expected Result**
The text should say something like:
_This transaction will delegate an amount of CCD to the L-pool. You must choose the amount to delegate._

**Actual Result**
The text currently says:
_This transaction will delegate an amount of CCD to an active baker. You must choose the amount to delegate, if you want to add rewards to the delegated amount._

**Versions**
- Software Version 1.4.0-beta.0

**Comment by mh-concordium** [comment]
Since there is inconsistency between account balances on MW and DW, I have discussed the matter with @jens-concordium  and we agreed to change the following string:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/98821384/163993932-f8e03b7a-479b-4334-8631-e2405c0a33b5.png">

to  "Delegation to baker pool  _id_"
