### ISSUE TITLE
Identity issuance crashes

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-desktop-wallet#296]
**Bug Description**

When entering the external flow in the identity issuance, this error appears:
![image (2)](https://user-images.githubusercontent.com/87635671/167109233-a4301c08-e084-4837-ae72-1026fa421a82.png)

(Happens consistenly in @mh-concordium's mac)

**Versions**
- 1.4.0-beta.2
- Mac (M1)

**Comment by orhoj** [comment]
@mh-concordium does this also happen to you on the current release (1.3.1)?

**Comment by mh-concordium** [comment]
I would have to try this specific release. I have used the previous one made for Delegation and that was working.

**Comment by orhoj** [comment]
What version was that?

**Comment by mh-concordium** [comment]
I believe that the failing one (this issue) was 1.4.0-beta.2.
Working one I have tested before were 1.4.0-beta.0 and 1.4.0-alpha.0.

**Comment by shjortConcordium** [comment]
A user have encountered this error on 1.3.1 (macOS)

**Comment by abizjak** [comment]
Please supply steps/context to reproduce, or close if the issue is deemed to be resolved.

**Comment by tschudid** [comment]
<img width="255" alt="bugreport" src="https://user-images.githubusercontent.com/14889202/174242533-d95ffd86-2ae6-4f76-abe4-e4d7560cd5fe.png">

Similar issue after upgrading from DW 1.3.1 to 1.4.1 on macos (intel).

**Comment by orhoj** [comment]
This happens due to the way windows are handled on macOS. If you close the main window (e.g. by pressing the X in the upper-left corner), then we have special macOS handling that keeps the application alive as this is the standard on macOS. However, as the window is killed when closed we now have a bunch of listeners with a reference to a destroyed window. This is why we get an error when trying to register a duplicate handler, and it is also the issue behind the image shown in this issue as it refers to a destroyed object.

**Comment by mh-concordium** [comment]
Verified on MacOS 1.4.2. 
First I have successfully reproduced both issues on v. 1.4.1, afterwards I have installed 1.4.2 and all seemed ok. I didn't see warning reported by Daniel neither warning  I saw before.
